# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    #sh("rm -r ~/Library/Developer/Xcode/DerivedData/*")
    precheck
    getVersion = get_version_number(xcodeproj: "Easy Bridge Tracker.xcodeproj", target: "Easy Bridge Tracker")
    increment_build_number(build_number: latest_testflight_build_number(version: getVersion) + 1, xcodeproj: "Easy Bridge Tracker.xcodeproj")
    getBuild = get_build_number(xcodeproj: "Easy Bridge Tracker.xcodeproj")
    build_app(scheme: "Easy Bridge Tracker", output_directory: "./Builds/#{getVersion}/#{getBuild}")
    upload_to_testflight
    notification(subtitle: "Finished Uploading", message: "Ready to test...", open: "https://appstoreconnect.apple.com/apps/1640954057/testflight/ios")
  end
    lane :getScreenshots do
    Dir.chdir("..") do
      #sh("ls")
      sh("sh './Promo Images/Remove Screenshots.sh'")
    end
    capture_screenshots(headless: false, clear_previous_screenshots: false, output_directory: "./Promo Images/Light Mode", dark_mode: false)
    capture_screenshots(headless: false, clear_previous_screenshots: false, output_directory: "./Promo Images/Dark Mode", dark_mode: true)
    Dir.chdir("..") do
      notification(subtitle: "Finished Taking Screenshots", message: "Ready to mockup...", open: "file:///~/Xcode/Easy-Bridge-Tracker/Promo%20Images/AppMockUp%20Studio.webarchive")
      sh("sh './Promo Images/Convert Screenshots.sh'")
      sh("sh './Promo Images/Remove png Screenshots.sh'")
    end
    #frame_screenshots(path: "./Promo Images")
  end
end
